source 'https://rubygems.org'

gem 'rails', '4.2.0'

gem 'coffee-rails', '~> 4.1.0'
gem 'dotenv'
gem 'faraday'
gem 'haml'
gem 'jquery-rails'
gem 'omniauth'
gem 'omniauth-oauth2'
gem 'sass-rails', '~> 5.0'
gem 'sqlite3'
gem 'turbolinks'
gem 'uglifier', '>= 1.3.0'

group :development, :test do
  gem 'byebug'
  gem 'web-console', '~> 2.0'
  gem 'spring'
end
