# Be sure to restart your server when you modify this file.

# Your secret key is used for verifying the integrity of signed cookies.
# If you change this key, all old signed cookies will become invalid!

# Make sure the secret is at least 30 characters and all random,
# no regular words or you'll be exposed to dictionary attacks.
# You can use `rake secret` to generate a secure secret key.

# Make sure the secrets in this file are kept private
# if you're sharing your code publicly.

development:
  secret_key_base: 1cf0239473673b8e321057721b2ab39cb9a15a5861b92167d21ef0fb0bd0a8eee83d34f095db1a15f9d9867a375e3a164dfc683c1bb5e12ae74ed842b4e796ff

test:
  secret_key_base: 761beddb8828e176d199f67d7adbfc4d220e94a8a053588036d0b04c264fcb0840727cd6f9a144a65f37066995870f508c469d0322f05df507d3d83dff9f845a

# Do not keep production secrets in the repository,
# instead read values from the environment.
production:
  secret_key_base: <%= ENV["SECRET_KEY_BASE"] %>
